# Generated by Django 5.1.3 on 2024-11-24 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('recipe_disc', models.TextField(blank=True, null=True)),
                ('recipe_name', models.CharField(max_length=40, unique=True)),
                ('recipe_img', models.CharField(default='not available', max_length=50, null=True)),
                ('recipe_created_at', models.DateTimeField(auto_now=True)),
                ('recipe_view_count', models.IntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe',
                'ordering': ['-recipe_view_count'],
            },
        ),
    ]
