# Generated by Django 5.1.3 on 2024-11-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_img',
            field=models.ImageField(blank=True, null=True, upload_to='Recipe_pictures/'),
        ),
    ]
