# Generated by Django 5.1.3 on 2024-11-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciepe_app', '0002_alter_recipe_recipe_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-recipe_created_at'], 'verbose_name': 'Recipe'},
        ),
    ]
